# This file is used to override the default settings in docker-compose.yml.
# You can use it to set environment variables or change the configuration of the services.
services:
  brain-wiz:
    environment:
      - NODE_ENV=development
  nginx:
    profiles:
      - proxy
  db:
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
