# docker-compose.dev.yml
services:
  # ---------------------------------------------------------------------------
  # Brain Wiz
  # ---------------------------------------------------------------------------
  brain-wiz:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=db
    container_name: server
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # PostgreSQL
  # ---------------------------------------------------------------------------
  db:
    image: postgres:16
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ---------------------------------------------------------------------------
  # Visualize Postgres
  # ---------------------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    user: root
    depends_on:
      - db
    restart: unless-stopped


volumes:
  postgres_data:
