/**
 * @file round-builder.ts
 * @owner server-squad
 * @description Pre-builds the round sequence for a game. When the room has a
 * host-built flow (`room.gameFlow`), it expands that flow into rounds: each
 * theme block becomes up to N distinct questions of that theme, and each
 * mini-game block becomes a procedural round generated by its registered
 * mini-game adapter (resolved via the block's `minigameKey`). When no flow is
 * set it falls back to the default mixed sequence (`ROUNDS.DEFAULT_SEQUENCE`):
 * quiz rounds interleaved with procedural mini-game rounds.
 */
import 'reflect-metadata'
import { BadRequestException, Injectable, Logger } from '@nestjs/common'
import { InjectRepository } from '@nestjs/typeorm'
import { randomUUID } from 'node:crypto'
import type { DeepPartial, Repository } from 'typeorm'
import { Question } from '../../entities/question.entity'
import { Round } from '../../entities/round.entity'
import { Room } from '../../entities/room.entity'
import { GameBlock } from '../../entities/game-block.entity'
import { RoundStatusEnum, ContentTypeEnum, BlockKindEnum } from '../../entities/enums'
import { ROUNDS, TIMER } from '@brain-wiz/config/game.config'
import {
  MAX_MINIGAME_TIME_SECONDS,
  MINIGAME_TIME_STEP_SECONDS,
  MIN_MINIGAME_TIME_SECONDS,
} from '@brain-wiz/shared/constants/flow.constants'
import type { RoundType } from '@brain-wiz/shared/types/index'
import { NotEnoughQuestionsError } from './game.errors'
import type { ProceduralRoundSeedInput } from './game.types'
import { MinigameRegistry } from './minigames/minigame-registry'

const DEFAULT_QUESTIONS_PER_BLOCK = 5

/** One planned round before it is persisted: either a quiz or a procedural round. */
interface QuizRoundSpec {
  kind: 'quiz'
  question: Question
}
interface ProceduralRoundSpec {
  kind: 'procedural'
  type: RoundType
  difficulty?: number
  timeLimitSeconds?: number
}
type RoundSpec = QuizRoundSpec | ProceduralRoundSpec

@Injectable()
export class RoundBuilder {
  private readonly logger = new Logger(RoundBuilder.name)

  public constructor(
    @InjectRepository(Question) private readonly questions: Repository<Question>,
    @InjectRepository(Round) private readonly rounds: Repository<Round>,
    @InjectRepository(Room) private readonly roomRepo: Repository<Room>,
    @InjectRepository(GameBlock) private readonly blocks: Repository<GameBlock>,
    private readonly minigames: MinigameRegistry
  ) {}

  /**
   * Build the round sequence. If the room has a custom flow, expand it; the
   * `count` argument is then only the fallback for flowless (MVP) games.
   */
  public async buildRounds(room: Room, count: number): Promise<Round[]> {
    const flow = room.gameFlow ?? []
    const plan = flow.length > 0 ? await this.planFromFlow(room) : await this.defaultPlan(count)

    if (plan.length === 0) {
      throw new NotEnoughQuestionsError(flow.length > 0 ? 1 : count, 0)
    }

    const built: Round[] = []
    for (let index = 0; index < plan.length; index += 1) {
      const spec = plan[index]
      if (!spec) continue
      if (spec.kind === 'quiz') {
        built.push(await this.saveQuizRound(room, index, spec.question))
      } else {
        built.push(
          await this.saveProceduralRound(
            room,
            index,
            spec.type,
            spec.difficulty,
            spec.timeLimitSeconds
          )
        )
      }
    }

    room.totalRounds = built.length
    await this.roomRepo.save(room)
    return built
  }

  /**
   * Expand a host-built flow into an ordered round plan. Each theme block
   * contributes up to its requested count of distinct questions of that theme,
   * never repeating a question within the game. Each mini-game block becomes a
   * procedural round driven by its registered adapter and per-item timer.
   */
  private async planFromFlow(room: Room): Promise<RoundSpec[]> {
    const catalog = await this.blocks.find()
    const blockById = new Map(catalog.map((b) => [b.id, b]))
    const pool = await this.questions.find()
    const byTheme = this.groupQuestionsByTheme(pool)

    const plan: RoundSpec[] = []
    let unknownMinigames = 0
    for (const item of room.gameFlow) {
      const block = blockById.get(item.blockId)
      if (!block) continue
      if (block.kind === BlockKindEnum.THEME && block.theme) {
        plan.push(...this.planThemeBlock(block.theme, item.questions, byTheme))
      } else if (block.kind === BlockKindEnum.MINIGAME && block.minigameKey) {
        plan.push(this.planMinigameBlock(block.minigameKey, item.timeLimitSeconds, item.difficulty))
      } else {
        unknownMinigames++
      }
    }

    this.warnUnknownBlocks(room, unknownMinigames)
    return plan
  }

  /** Group the question pool by theme, each group pre-shuffled for distinct hand-out. */
  private groupQuestionsByTheme(pool: Question[]): Map<string, Question[]> {
    const byTheme = new Map<string, Question[]>()
    for (const q of pool) {
      const list = byTheme.get(q.theme) ?? []
      list.push(q)
      byTheme.set(q.theme, list)
    }
    for (const [theme, list] of byTheme) {
      byTheme.set(theme, this.shuffled(list))
    }
    return byTheme
  }

  /** Take up to `want` distinct questions of `theme`, consuming them from the pool. */
  private planThemeBlock(
    theme: string,
    want: number | undefined,
    byTheme: Map<string, Question[]>
  ): QuizRoundSpec[] {
    const available = byTheme.get(theme) ?? []
    const count = want ?? DEFAULT_QUESTIONS_PER_BLOCK
    const specs: QuizRoundSpec[] = []
    for (let n = 0; n < count; n++) {
      const next = available.pop()
      if (!next) break
      specs.push({ kind: 'quiz', question: next })
    }
    return specs
  }

  /** Build a procedural round spec for a mini-game block, honoring its per-item timer and difficulty. */
  private planMinigameBlock(
    minigameKey: string,
    timeLimitSeconds?: number,
    difficulty?: number
  ): ProceduralRoundSpec {
    const spec: ProceduralRoundSpec = { kind: 'procedural', type: minigameKey as RoundType }
    if (timeLimitSeconds !== undefined) {
      spec.timeLimitSeconds = timeLimitSeconds
    }
    if (difficulty !== undefined) {
      spec.difficulty = difficulty
    }
    return spec
  }

  /** Log a single warning summarizing any blocks that could not be planned. */
  private warnUnknownBlocks(room: Room, unknownMinigames: number): void {
    if (unknownMinigames > 0) {
      this.logger.warn(
        `Skipped ${unknownMinigames} unrecognized block(s) in room ${room.id}: ` +
          `blocks must be a theme with questions or a mini-game with a minigameKey.`
      )
    }
  }

  /**
   * Flowless fallback: the default mixed sequence of quiz + procedural rounds.
   * Quiz slots are filled with distinct random questions.
   */
  private async defaultPlan(count: number): Promise<RoundSpec[]> {
    const sequence = this.roundSequence(count)
    const quizCount = sequence.filter((type) => type === 'quiz').length
    const pool = await this.questions.find()
    if (pool.length < quizCount) {
      throw new NotEnoughQuestionsError(quizCount, pool.length)
    }
    const quizQuestions = this.shuffled([...pool]).slice(0, quizCount)

    const plan: RoundSpec[] = []
    let quizIndex = 0
    for (const type of sequence) {
      if (type === 'quiz') {
        const question = quizQuestions[quizIndex]
        quizIndex += 1
        if (!question) {
          throw new NotEnoughQuestionsError(quizCount, quizQuestions.length)
        }
        plan.push({ kind: 'quiz', question })
      } else {
        plan.push({ kind: 'procedural', type })
      }
    }
    return plan
  }

  private roundSequence(count: number): RoundType[] {
    const sequence: RoundType[] = []
    for (let index = 0; index < count; index += 1) {
      sequence.push(ROUNDS.DEFAULT_SEQUENCE[index % ROUNDS.DEFAULT_SEQUENCE.length] ?? 'quiz')
    }
    return sequence
  }

  private createProceduralRoundSeed({ roomId, roundId, type }: ProceduralRoundSeedInput): string {
    return `${roomId}:${roundId}:${type}`
  }

  private async saveQuizRound(room: Room, index: number, question: Question): Promise<Round> {
    const round = this.rounds.create({
      roomId: room.id,
      roundIndex: index,
      status: RoundStatusEnum.PENDING,
      contentType: ContentTypeEnum.QUESTION,
      gameType: 'quiz',
      timeLimitSeconds: TIMER.QUESTION_SECONDS,
      question,
    })
    return this.rounds.save(round)
  }

  private async saveProceduralRound(
    room: Room,
    index: number,
    type: RoundType,
    difficulty?: number,
    requestedTimeLimitSeconds?: number
  ): Promise<Round> {
    const adapter = this.minigames.get(type)
    if (!adapter) {
      throw new BadRequestException(`No minigame adapter registered for round type "${type}"`)
    }
    const roundId = randomUUID()
    const timeLimitSeconds = this.proceduralRoundSeconds(type, requestedTimeLimitSeconds)
    const seed = this.createProceduralRoundSeed({
      roomId: room.id,
      roundId,
      type,
    })
    const generated = adapter.createRound({
      roundId,
      seed,
      roundIndex: index,
      timeLimitSeconds,
      ...(difficulty !== undefined ? { difficulty } : {}),
    })
    const round: Round = this.rounds.create({
      id: roundId,
      roomId: room.id,
      roundIndex: index,
      status: RoundStatusEnum.PENDING,
      contentType: ContentTypeEnum.PUZZLE,
      gameType: generated.type,
      seed: generated.seed,
      publicState: generated.publicState,
      privateState: generated.privateState,
      scoringConfig: generated.scoringConfig,
      timeLimitSeconds,
    } as DeepPartial<Round>)

    return this.rounds.save(round)
  }

  private proceduralRoundSeconds(type: RoundType, requested?: number): number {
    const fallback = this.defaultProceduralRoundSeconds(type)
    const desired = Number.isFinite(requested) ? Number(requested) : fallback
    const stepped = Math.round(desired / MINIGAME_TIME_STEP_SECONDS) * MINIGAME_TIME_STEP_SECONDS
    return Math.max(MIN_MINIGAME_TIME_SECONDS, Math.min(MAX_MINIGAME_TIME_SECONDS, stepped))
  }

  private defaultProceduralRoundSeconds(type: RoundType): number {
    if (type === 'sliding-puzzle') {
      return TIMER.SLIDING_PUZZLE_SECONDS
    }

    if (type === 'vault-rush') {
      return TIMER.VAULT_RUSH_SECONDS
    }

    return TIMER.QUESTION_SECONDS
  }

  /** Fisher–Yates shuffle, returning the same array reference (shuffled in place). */
  private shuffled<T>(items: T[]): T[] {
    for (let i = items.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1))
      const a = items[i]
      const b = items[j]
      if (a === undefined || b === undefined) continue
      items[i] = b
      items[j] = a
    }
    return items
  }
}
